Cloud/urls.py
from django.contrib import admin
from django.urls import path, include
from Cloud.api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', api.urls, name='api'),
    path('coworking/', include('Coworking.urls')),
]

Coworking/urls.py
from django.urls import path

from Coworking import views


app_name = 'coworking'
urlpatterns = [
    path('info/', views.create_request, name='info'),
    path('rate/', views.rate, name='rate'),
]

Coworking/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Coworking(models.Model):
    name = models.CharField(max_length=255)
    places_number = models.IntegerField()

    objects = models.Manager()

    class Meta:
        db_table = 'coworking'


class OccupiedSpaceInfo(models.Model):
    coworking = models.ForeignKey(to=Coworking, on_delete=models.CASCADE)
    places_occupied = models.IntegerField()
    time = models.DateTimeField(default=datetime.now())

    objects = models.Manager()

    class Meta:
        db_table = 'occupied_space'


class Rate(models.Model):
    coworking = models.ForeignKey(Coworking, on_delete=models.CASCADE)
    mark = models.IntegerField()

    objects = models.Manager()

    class Meta:
        db_table = 'rate'

Coworking/views.py
from django.shortcuts import render
from django import forms
from django.views.decorators.http import require_POST
from . import models

from Coworking.models import Coworking, OccupiedSpaceInfo


class CreateRequest(forms.Form):
    coworking_name = forms.ChoiceField(
        choices=(('Kronverkskii 2-nd floor', 'Kronverkskii 2-nd floor'),
                 ('Kronverkskii 3-rd floor', 'Kronverkskii 3-rd floor'),
                 ('Lomonosova 2-nd floor', 'Lomonosova 2-nd floor'),
                 ('Lomonosova 4-th floor', 'Lomonosova 4-th floor'),
                 ),
    )


# Create your views here.
def create_request(request):
    f = CreateRequest(request.GET)

    if f.is_valid():
        coworking_name = f.data.get('coworking_name')
        coworking = Coworking.objects.get(name=coworking_name)
        last_occupied_info = OccupiedSpaceInfo.objects.filter(coworking=coworking).order_by('-time')[0]
        free_place_number = coworking.places_number - last_occupied_info.places_occupied
        return render(request, 'request.html', context={
            'answer': f'Number of free places at {coworking_name}: {free_place_number}'
        })

    return render(request, 'request.html', context={
            'answer': 'Something goes wrong. Try again'
        })


class Rate(forms.Form):
    CHOICES = (('Kronverkskii 2-nd floor', 'Kronverkskii 2-nd floor'),
               ('Kronverkskii 3-rd floor', 'Kronverkskii 3-rd floor'),
               ('Lomonosova 2-nd floor', 'Lomonosova 2-nd floor'),
               ('Lomonosova 4-th floor', 'Lomonosova 4-th floor'),
               )
    coworking_name = forms.ChoiceField(choices=CHOICES)
    mark = forms.IntegerField(min_value=0, max_value=10)


@require_POST
def rate(request):
    f = Rate(request.POST)

    if f.is_valid():
        coworking_name = f.cleaned_data['coworking_name'].lower()
        mark = f.cleaned_data['mark']
        coworking = Coworking.objects.get(name=coworking_name)
        rate = models.Rate(coworking=coworking, mark=mark)
        rate.save()
        return render(request, 'rate.html', context={
            'answer': 'Thanks for your mark'
        })

    return render(request, 'rate.html', context={
            'answer': "Your mark has not been saved. Please try again"
        })

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
</head>
<body>
    <p class="link"><a href="/api/request">Free places</a></p>
    <p class="link"><a href="/api/rate">Rate co-working</a></p>
</body>
</html>

templates/rate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rate</title>
</head>
<body>
    <a href='/api/'>Main</a>
    <form action="{% url 'coworking:rate' %}" method="post" class="form-example">
        {% csrf_token %}
        <div class="form-example">
          <label for="coworking_name">Coworking name: </label>
          <select name="coworking_name" id="name" required>
              <option value="Kronverkskii 2-nd floor">Kronverkskii 2-nd floor</option>
              <option value="Kronverkskii 3-rd floor">Kronverkskii 3-rd floor</option>
              <option value="Lomonosova 2-nd floor">Lomonosova 2-nd floor</option>
              <option value="Lomonosova 4-th floor">Lomonosova 4-th floor</option>
          </select>
        </div>
        <div>
            <label for="mark">Mark:</label>
            <input type="number" name="mark" value="5" min="0" max="10" required/>
        </div>
        <div class="form-example">
          <input type="submit" value="Rate">
        </div>
    </form>
    <div>
        <p>{{ answer }}</p>
    </div>
</body>
</html>

templates/request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Request</title>
</head>
<body>
    <a href='/api/'>Main</a>
    <form action="{% url 'coworking:info' %}" method="get" class="form-example">
        <div class="form-example">
          <label for="coworking_name">Coworking name: </label>
          <select name="coworking_name" id="name" required>
              <option value="Kronverkskii 2-nd floor">Kronverkskii 2-nd floor</option>
              <option value="Kronverkskii 3-rd floor">Kronverkskii 3-rd floor</option>
              <option value="Lomonosova 2-nd floor">Lomonosova 2-nd floor</option>
              <option value="Lomonosova 4-th floor">Lomonosova 4-th floor</option>
          </select>
        </div>
        <div class="form-example">
          <input type="submit" value="Create Request">
        </div>
    </form>
    <div>
        <p>{{ answer }}</p>
    </div>
</body>
</html>